version: '3'

services:
  db: 
    image: postgres
    ports:
      - '5430:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=local